app:
  name: "kafka-commit-async"
server:
  port: 9002
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
kafka:
  bootstrapServers:
    -
      name: "local"
      bootstrap.servers: "localhost:29092"
#      bootstrap.servers: "172.25.0.5:9095,172.25.0.3:9094,172.25.0.4:9093"