app:
  name: "kafka-commit-async"
server:
  port: 9002
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
kafka:
  bootstrapServers:
    -
      name: "local"
      bootstrap.servers: "localhost:29092"